stages:         
  - deploy
test_deploy_with_agent:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    #- kubectl config get-contexts
<<<<<<< HEAD
    - kubectl config use-context d7769/advanceddigitalq:k8s-agent
    - kubectl apply -f  ./kubernetes/opentelemetry-demo.yaml   -n otel-demo
    - kubectl get pods -n otel-demo
=======
    - kubectl config use-context d7769/adv_o11y_eos:k8s-agent-o11y
    - kubectl apply -f  ./kubernetes/opentelemetry-demo-updated.yaml   -n otel-demo-o11y
    - kubectl get pods -n otel-demo-o11y
>>>>>>> 1a38e439684c06a3f6744fad2f05b5a10c8c7440
  when: manual