stages:         
  - deploy
test_deploy_with_agent:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    #- kubectl config get-contexts
    - kubectl config use-context d7769/adv_o11y_eos:k8s-agent-o11y
    - kubectl apply -f  ./kubernetes/opentelemetry-demo-updated.yaml   -n otel-demo-o11y
    - kubectl get pods -n otel-demo-o11y
  when: manual